title: <p align="center"> Arvind Rangarajan </p>

logo: "/Images/profile.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/arvindrangarajan1/">LinkedIn</a> |
  <a href="https://github.com/arvindrangarajan2024">GitHub</a>
  </p>
  
  <p align="justify">
  I am a product marketer with a lot of passion for software development and coding.
  </p>
  
theme: jekyll-theme-minimal
#google_analytics: UA-145578661-1 # Google Analytics tracking ID
